apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
spec:
<<<<<<< HEAD
  replicas: 6
=======
  replicas: 4
>>>>>>> parent of 13d3ed6 (argo4)
  selector:
    matchLabels:
      app: nginx-app

  template:
    metadata:
      labels:
        app: nginx-app

    spec:
      containers:
      - name: nginx-container
        image: nginx:latest

        ports:
        - containerPort: 80
